global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'chaos_api'
    static_configs:
      - targets: ['chaos_api:8000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - "alert_rules.yml"
